/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizproject.TeachersPanel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
/**
 *
 * @author mzjet
 */
public class addDeleteStudent extends javax.swing.JFrame {

    /**
     * Creates new form addDeleteStudent
     */
    public addDeleteStudent() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setSeatNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        setName = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();
        deleteStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addStudent1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Manage Student");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Seat Number :");

        setSeatNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setSeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSeatNumberActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Name :");

        setName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        setName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameActionPerformed(evt);
            }
        });

        addStudent.setBackground(new java.awt.Color(255, 255, 255));
        addStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        deleteStudent.setBackground(new java.awt.Color(255, 255, 255));
        deleteStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteStudent.setText("Delete Student");
        deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentActionPerformed(evt);
            }
        });

        try{
            // my code
            JSONParser parser = new JSONParser();

            Object obj = parser.parse(new FileReader("./Data/QuizScore.json"));

            JSONArray student = (JSONArray) obj;

            Object[] array = student.toArray();

            Object[][] mainData = new Object[array.length][3];

            for(int i=0; i<array.length; i++){

                JSONObject StudentObject = (JSONObject) array[i];

                mainData[i][0] = i+1+"";
                mainData[i][1] = StudentObject.get("Name");
                mainData[i][2] = StudentObject.get("SeatNumber");

            }

            String[] columnNames = {"S.No","Name","Seat Number"};

            TableModel tableModel = new DefaultTableModel(mainData, columnNames);
            table.setModel(tableModel);
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();
            if (defaults.get("Table.alternateRowColor") == null)
            defaults.put("Table.alternateRowColor", new Color(240, 240, 240));

            TableCellRenderer rendererFromHeader = table.getTableHeader().getDefaultRenderer();
            JLabel headerLabel = (JLabel) rendererFromHeader;
            headerLabel.setHorizontalAlignment(JLabel.CENTER);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );

            table.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
            //        table.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
            table.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );

            table.setFont(new Font("Tahome",Font.PLAIN,15));
            int height = table.getRowHeight();
            table.setRowHeight(height+10);

            //        table.setEnabled(false);

            JTableHeader Theader = table.getTableHeader();
            Theader.setFont(new Font("Tahome",Font.BOLD,20) );

            Theader.setBackground(Color.BLUE);
            Theader.setForeground(Color.BLACK);

            table.getTableHeader().setOpaque(false);

            table.getTableHeader().setBackground(Color.BLACK);
        }catch(Exception e){e.printStackTrace();};
        jScrollPane1.setViewportView(table);

        addStudent1.setBackground(new java.awt.Color(255, 255, 255));
        addStudent1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addStudent1.setText("Close");
        addStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudent1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteStudent))
                            .addComponent(addStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setSeatNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setName)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSeatNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setSeatNumberActionPerformed

    private void setNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setNameActionPerformed
public void addStudent(String name, String seatnumber)throws Exception{

        JSONParser parser = new JSONParser();

        Object obj = parser.parse(new FileReader("./Data/QuizScore.json"));

        JSONArray student = (JSONArray) obj;

//        Object[] array = student.toArray();
//        String flag = "false";
//        int index =0; 

        Map<String,String> newdata = new HashMap<String,String>();
        newdata.put("Name", name);
        newdata.put("SeatNumber", seatnumber);
        newdata.put("Score", "");

        student.add(newdata);

        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json = gson.toJson(student);
        // System.out.println(json);

        FileWriter file = new FileWriter("./Data/QuizScore.json");
        file.write(json);
        file.close();
        

    }

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        try{
            JSONParser parser = new JSONParser();

            Object obj = parser.parse(new FileReader("./Data/QuizScore.json"));

            JSONArray student = (JSONArray) obj;

            Object[] array = student.toArray();

            Object[][] mainData = new Object[array.length][3];
            int flag = 0;
            
            if(setName.getText().equals("") || setSeatNumber.getText().equals("")){ 
                JOptionPane.showMessageDialog(this, "Please Enter All Data"); 
                setName.setText("");
                setSeatNumber.setText(""); }
            else{
                
                for(int i=0; i<array.length; i++){
                    JSONObject StudentObject = (JSONObject) array[i];
                    if(StudentObject.get("SeatNumber").toString().equals(setSeatNumber.getText().toUpperCase())){
                        flag = 1;
                        JOptionPane.showMessageDialog(this, "Seat Number: " + setSeatNumber.getText() + " Already Exist");
                        setName.setText("");
                        setSeatNumber.setText("");
                        break;
                    }
                    else{ flag = 0;}
                }
                
                if(flag == 0){
                    
                    addStudent(setName.getText(),setSeatNumber.getText().toUpperCase());
                    
                    JOptionPane.showMessageDialog(this, "Added Successfully");
                    
                    DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
                    String sNo = Integer.toString(array.length+1);
                    String[] data = {sNo, setName.getText(),setSeatNumber.getText().toUpperCase()};
                    tblModel.addRow(data);
                    setName.setText("");
                    setSeatNumber.setText("");
            }
                }
            
            
            
        }catch(Exception e){ e.printStackTrace();}
        
        
        
    }//GEN-LAST:event_addStudentActionPerformed
public void deleteStudent(String seatnumber) throws Exception{
    
        JSONParser parser = new JSONParser();

        Object obj = parser.parse(new FileReader("./Data/QuizScore.json"));

        JSONArray student = (JSONArray) obj;

        Object[] array = student.toArray();
        int index=0;
        
        for(int i=0; i<array.length; i++){

            JSONObject StudentObject = (JSONObject) array[i];
            if(StudentObject.get("SeatNumber").equals(seatnumber) == true){
                index = i;
            }       
        }

         student.remove(index);
         
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        String json = gson.toJson(student);

        FileWriter file = new FileWriter("./Data/QuizScore.json");
        file.write(json);
        file.close();

    }
    private void deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentActionPerformed
        // TODO add your handling code here:
        try{
            JSONParser parser = new JSONParser();

            Object obj = parser.parse(new FileReader("./Data/QuizScore.json"));

            JSONArray student = (JSONArray) obj;

            Object[] array = student.toArray();
        
            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            if( table.getSelectedRowCount() == 1){ 
                
                JSONObject StudentObject = (JSONObject) array[table.getSelectedRow()];
                String seatno = StudentObject.get("SeatNumber").toString();
                
                deleteStudent(seatno);
                
                tblModel.removeRow(table.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
                
            }else{
                if(table.getRowCount() == 0){JOptionPane.showMessageDialog(this, "Table is Empty");}
                else{JOptionPane.showMessageDialog(this, "Please Select Single Row to Delete");}
            }
          
        }catch(Exception e){e.printStackTrace();};
    }//GEN-LAST:event_deleteStudentActionPerformed

    private void addStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudent1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_addStudent1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDeleteStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JButton addStudent1;
    private javax.swing.JButton deleteStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField setName;
    private javax.swing.JTextField setSeatNumber;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
